export default {
  login: "knaveen96",
  id: 82062695,
  node_id: "MDQ6VXNlcjgyMDYyNjk1",
  avatar_url: "https://avatars.githubusercontent.com/u/82062695?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/knaveen96",
  html_url: "https://github.com/knaveen96",
  followers_url: "https://api.github.com/users/knaveen96/followers",
  following_url: "https://api.github.com/users/knaveen96/following{/other_user}",
  gists_url: "https://api.github.com/users/knaveen96/gists{/gist_id}",
  starred_url: "https://api.github.com/users/knaveen96/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/knaveen96/subscriptions",
  organizations_url: "https://api.github.com/users/knaveen96/orgs",
  repos_url: "https://api.github.com/users/knaveen96/repos",
  events_url: "https://api.github.com/users/knaveen96/events{/privacy}",
  received_events_url: "https://api.github.com/users/knaveen96/received_events",
  type: "User",
  site_admin: false,
  name: "Naveen Kuragayala",
  company: "Student",
  blog: "",
  location: "Indianapolis, Indiana, USA",
  email: null,
  hireable: null,
  bio: "- Problem Solving <3\r\n- Java \r\n- React.js\r\n",
  twitter_username: "IdontTweeett",
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-04-06T21:41:39Z",
  updated_at: "2022-06-10T23:19:35Z"
}
